services:
  postgres_db:
    container_name: postgres_db
    build:
      context: ./postgres_pgvector
    hostname: "127.0.0.1"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - ./postgres_pgvector/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - thesis-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - thesis-net

networks:
  thesis-net:
    external: true

volumes:
  postgres_data:
