services:
  nest-service:
    build:
      context: ./core-service/.
    volumes:
      - ./src:/usr/src/app/src
      - ./package*.json:/usr/src/app/package*.json
    ports:
      - "8001:8001"
    command: npm run start:prod
    env_file: ./core-service/.env
    networks:
      - thesis-net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  scraping-service:
    build:
      context: ./scraping-service/.
      dockerfile: Dockerfile
    image: scraping-service:latest
    container_name: scraping-service
    restart: unless-stopped
    env_file:
      - ./scraping-service/.env
    ports:
      - "5003:5003"
    networks:
      - thesis-net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  retrieval-service:
    build:
      context: ./retrieval-service
      dockerfile: Dockerfile
    image: retrieval-service:latest
    container_name: retrieval-service
    restart: unless-stopped
    env_file:
      - ./retrieval-service/.env
    ports:
      - "8002:8002"
    networks:
      - thesis-net

  embedding-service:
    build:
      context: ./embedding-service
      dockerfile: Dockerfile
    image: embedding-service:latest
    container_name: embedding-service
    restart: unless-stopped
    env_file:
      - ./embedding-service/.env
    ports:
      - "5002:5002"
    networks:
      - thesis-net
  
  frontend:
    build:
      context: ./thesis-fe
      dockerfile: Dockerfile
    volumes:
      - ./thesis-fe:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - thesis-net


networks:
  thesis-net:
    external: true
    driver: bridge
