# ---------- Stage 1: Build ----------
  FROM node:20.19.1-alpine AS builder

  # 1. Create app dir
  WORKDIR /usr/src/app
  
  # 2. Install build dependencies
  # Copy only package manifests first to leverage Docker cache
  COPY package*.json tsconfig*.json ./
  COPY nest-cli.json ./
  
  # If you use path aliases, copy tsconfig-paths config
  COPY src ./src

  # For DNS calls
  RUN apk update && apk add --no-cache bind-tools
  
  # 3. Install & build
  RUN npm ci && \
      npm run build
  
  # ---------- Stage 2: Production ----------
  FROM node:20.19.1-alpine
  
  WORKDIR /usr/src/app
  
  # 1. Copy only the production artifacts
  COPY --from=builder /usr/src/app/dist ./dist
  COPY package*.json ./
    
  # 2. Install only prod deps
  ENV NODE_ENV=production
  RUN npm ci --omit=dev
  
  # 3. (Optional) create non-root user
  RUN addgroup -S nest && adduser -S -G nest nest
  USER nest
  
  # 4. Expose and launch
  EXPOSE 8001
  CMD ["node", "dist/main.js"]
  