# Use Node.js version 20.3.1 as the base image
FROM node:20.3.1

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 6543 for the NestJS service
EXPOSE 6543

# Run the NestJS service in development mode with file watching
CMD [ "npm", "run", "start:dev" ]
